### ISSUE TITLE
Copy Paste

### ISSUE THREAD

**Issue by holgerschochwitz** [EWSoftware/ListControls#2]
Hi,
can you insert a copyRow and pasteRow function?
Or can you explain me, how can i use Copy and Paste in the control.

Thank you

Holger

**Comment by EWSoftware** [comment]
I assume you're referring to the `DataList` control.  Copying and pasting from the clipboard is rather application specific so it's probably best handled by the form on which the data list control resides.  I'd suggest perhaps adding a `KeyDown` or `KeyPress` event for the data list and handing the common copy/paste key combinations.

The `SelectionStart` and `SelectionEnd` properties on the `DataList` control can be used to get the range of selected row headers.  You can then use that range to get the item or items to copy to the clipboard.  Pasting would be a matter of getting the information from the clipboard and appending clones of those items to the data source.  Below is a rough idea of the process for copying:

``` C#
int selStart = dataList.SelectionStart, selEnd = dataList.SelectionEnd;

if(selStart == -1)
    selStart = selEnd = dataList.CurrentRow;

dataList.CommitChanges();

while(selStart <= selEnd)
{
    object row = dataList.ListManager.List[selStart];

    ... Make a copy, add it to an array etc. ...

    selStart++;
}

... Copy the array etc. to the clipboard ...
```

**Comment by holgerschochwitz** [comment]
Can i create a new row in the datalList without a refresh?
I get an error when I try this:

`Dim sourceRow As DataRowView = newDR.ListManager.List.Item(1)

newDR.ListManager.List.Insert(newDR.CurrentRow, sourceRow.Row.ItemArray.Clone)
`

**Comment by EWSoftware** [comment]
Sorry, I somehow managed to miss this one.  You didn't list what the error was but I assume that should work.  An alternative as shown in the demo code is to [add the row directly to the table](https://github.com/EWSoftware/ListControls/blob/master/Demos/ListControlDemoCS/DataListTestForm.cs#L301).
