### ISSUE TITLE
Support for attributes

### ISSUE THREAD

**Issue by desarrollo03TR** [EWSoftware/ListControls#3]
Attributes like DisplayName or ReadOnly could be useful.

**Comment by EWSoftware** [comment]
You'll need to be more specific.  In regards to what?

**Comment by desarrollo03TR** [comment]
For example, with this class:

    public class Person
    {
        [Browsable(false)]
        public string FirstName { get; set; }

        [Browsable(false)]
        public string LastName {get;set;}

        [DisplayName("Full Name")]
        public string FullName => $"{FirstName} {LastName}";
    }

If a MultiColumnComboBox is binded with a List< Person>, the properties with Browsable(false) attribute will not generate columns, and the properties with DisplayName will generate columns with the specified name.

**Comment by EWSoftware** [comment]
Took a while to get to this.  It turns out .NET 8 supports Browsable and DisplayName automatically.  I've added support for .NET 4.8.
