### ISSUE TITLE
Assigning image to CheckBoxList item

### ISSUE THREAD

**Issue by LordChariot** [EWSoftware/ListControls#5]
I see no way to assign a specific image (from an imageList) to an individual CheckBoxItem.
The displayed image is simply an incrementing modulus of the imageList length.
For example the ExtendedTreeView has a StateImageList and can be set with the TreeNode.StateImageKey.
I can find now way of doing this in CheckBoxList.

**Comment by EWSoftware** [comment]
There isn't a way directly through the checked list box.  The image indexes on each checkbox control are set to the corresponding position of the checkbox within the list when created.  If there are more checkboxes than images, it wraps around to the start of the list.  Indirectly, you can change the image index using the `ButtonPanel` property to access each individual checkbox control.  For example:

```
((CheckBox)checkedListBox.ButtonPanel.Controls[checkedListBox.SelectedIndex]).ImageIndex = newIndex;
```

It's not ideal but it will work.

**Comment by LordChariot** [comment]
Thank you for that. That does set the image to the right value.
But now that I have that, the tops of each image (16x16) are clipped by 2-3 pixels.
I've been playing with the paddings and margins, but nothing seems to make a difference.
I see the same happening on your CheckBoxListTestForm as well.
Any suggestion on adjusting the height on the list item to allow the full image?

**Comment by EWSoftware** [comment]
Changing the `FlatStyle` property on the checkbox list control to either `Flat` or `Popup` works around the issue.  I'm not sure if it's an issue with the control layout or the underlying checkbox controls themselves.

**Comment by EWSoftware** [comment]
This is fixed and an update has been published.  I increased the item height when an image list is used.

**Comment by LordChariot** [comment]
Thank you. This works much better, and also fixes an issue where the displayed text of a list item was too close to the image and slightly overlapped by about 1 pixel or so.
