### ISSUE TITLE
MultiColumnComboBox Multiple column Selection? is it possible

### ISSUE THREAD

**Issue by robdob** [EWSoftware/ListControls#6]
Hi,

How are you?

Is it possible to select a specific item in a different column?

I have a list of 100 items which I want to display within a combobox, I would like to have 20 items per column across 5 columns and allow the user to make a selection of any item across the 5 columns of data being displayed, i.e. see below:, is this possible, if so could you please tell me how?

Item 1   Item 6   Item 11   Item 16   Item 21   Item 26
Item 2   Item 7   Item 12   Item 17   Item 22   Item 27
Item 3   Item 8   Item 13   Item 18   Item 23   Item 28
Item 4   Item 9   Item 14   Item 19   Item 24   Item 29
Item 5   Item 10 Item 15   Item 20   Item 25   Item 30

Thanks so much on advance..

**Comment by EWSoftware** [comment]
No, that isn't possible with the combo box.  Multi-column refers to showing multiple different columns from the data source (a grid), not a single column value going across and down.  The checkbox list and radio button list controls do allow that layout but they would take up more space on the form naturally.
