### ISSUE TITLE
Change Border Colour

### ISSUE THREAD

**Issue by MattH-Work** [EWSoftware/ListControls#7]
Is it possible to change to border colour, or more specifically, remove the border?

I'm overlaying your multi column combobox control onto another control in an effort to maintaine some visual consistency with other controls on my form

![image](https://user-images.githubusercontent.com/84494183/164031323-e5c65800-7878-4f36-8b23-0bd024571eaa.png)

Cheers

Matt

**Comment by MattH-Work** [comment]
"FlatStyle = Flat" gets me close, but only when backcolor of each control is a light colour

**Comment by MattH-Work** [comment]
With FlatStyle=Flat, enabled control works well (with light backround colours)
but
When Enabled = False, the border is still diaplayed

![image](https://user-images.githubusercontent.com/84494183/164191793-c6c19132-be5c-431a-86ad-101ec12ded0e.png)

**Comment by EWSoftware** [comment]
When themed (style is not Flat or Popup), it uses the theme style for all aspects of the control.  When flat or popup, it always uses the solid border style and system color.  A property could be added to set the border style to use when using the flat or popup style.
