### ISSUE TITLE
Drag and drop MultiColumnComboBox onto WinForm fails

### ISSUE THREAD

**Issue by Aniobodo** [EWSoftware/ListControls#8]
![Screenshot 2022-11-03 203703](https://user-images.githubusercontent.com/53254182/199817900-e46e2868-fcdc-4787-8503-b9be7e754070.png)

The above is the error message displayed on attempt to add MultiColumnComboBox to WinForm in .Net 6.

**Comment by EWSoftware** [comment]
The list controls currently only support .NET Framework 4.0 to 4.8.  I haven't done anything with them yet to support .NET 6.  Most will likely work once rebuilt to support it but it's doubtful the MultiColumnComboBox will without reworking it as it uses the DataGrid control which I don't think is available under .NET 6.0.  It would have to be updated to use the DataGridView instead if possible.

**Comment by Aniobodo** [comment]
Thank you Eric. I will continue to check if you manage to take it to .Net 6 and above.

**Comment by EWSoftware** [comment]
I've added support for .NET 6.0 and later.  Version 2023.4.9.0 is available on NuGet.
